language: csharp
dotnet: 2.0.0
mono: none
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
os:
  - linux
  - osx
sudo: false
install:
  - cd ./friends-core/src/
  - dotnet restore
script:
  - dotnet test FriendsLang.Compiler.Tests
  - dotnet test FriendsLang.Repl.Tests
